### ISSUE TITLE
Not able to clone the project

### ISSUE THREAD

**Issue by LoganDupont** [ultimatecourses/angular-basics-src#1]
If you try to clone the project after you forked from this repo you receive an error.
`error: invalid path '05-Rendering Flows/09-use-ng-switch-for-case-rendering/Icon?'
fatal: unable to checkout working tree`
![afbeelding](https://user-images.githubusercontent.com/6780720/187069895-113698a6-0e2b-49c2-b84f-573ad4de0935.png)

**Comment by LoganDupont** [comment]
It seems that in a lot of exercises and inside multiple folders of an exercise you have corrupt Icon files which are causing this issue.

**Comment by mangelo123** [comment]
Can someone please fix this issue? I cannot download the source that comes with this course!

**Comment by toddmotto** [comment]
@mangelo123 What error are you seeing?

**Comment by toddmotto** [comment]
This repo is merely to give access to the full source, what you need to do is start with the seed project and install that first:
https://github.com/ultimatecourses/angular-basics-seed

Then, if you want to run any code examples, copy the src/ folder into your installed project :)

**Comment by mangelo123** [comment]
![image](https://user-images.githubusercontent.com/1855917/220423958-b526463f-ade1-4c03-8b25-4b9af7d3c1eb.png)

**Comment by toddmotto** [comment]
I’ve removed Icon from that directory :)

**Comment by LoganDupont** [comment]
Actually it's not only that one. Each time you remove the Icon a new invalid path with be displayed when cloning the project. 
![afbeelding](https://user-images.githubusercontent.com/6780720/220463649-8bc60218-5ad8-4bec-8459-364ad344bb4e.png)

**Comment by mangelo123** [comment]
error: invalid path '05-Rendering Flows/09-use-ng-switch-for-case-rendering/src/Icon?'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by toddmotto** [comment]
All `Icon` removed, fully cloneable now - cheers guys
